version: "3"
services:
  goodwatt-database:
    image: mdillon/postgis:latest
    container_name: goodwatt-database
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/logs:/var/log/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - webappnetwork

  goodwatt-minio:
    image: minio/minio
    container_name: goodwatt-minio
    ports:
      - "9001:9000"
    restart: always
    volumes:
      - ./volumes/minio/data:/data
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    networks:
      - webappnetwork

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - net-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-vhost:/etc/nginx/vhost.d
      # #- ./nginx.tmpl:/app/nginx.tmpl
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt-nginx-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy
    restart: always
    networks:
      - net-nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
    depends_on:
      - nginx-proxy

networks:
  net-nginx-proxy:
    external:
      name: nginx-proxy
  webappnetwork:
    driver: bridge
