version: "3"
services:
  kit-lenid-client:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.client
      args:
        - REACT_APP_NODE_ENV=${REACT_APP_NODE_ENV}
        - REACT_APP_API=${REACT_APP_API}
        - REACT_APP_MINIO=${REACT_APP_MINIO}
    restart: always
    environment:
      VIRTUAL_HOST: ${CLIENT_VIRTUAL_HOST}
      VIRTUAL_PORT: ${CLIENT_VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${CLIENT_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${CLIENT_LETSENCRYPT_EMAIL}
    networks:
      - webappnetwork
      - default

  kit-lenid-server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.server
      args:
        - NODE_ENV=${NODE_ENV}
        - WEBSITE_URL=${WEBSITE_URL}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - POSTGRES_DB=${POSTGRES_DB}
        - DATABASE_URL=${DATABASE_URL}
        - MINIO_ENDPOINT=${MINIO_ENDPOINT}
        - MINIO_PORT=${MINIO_PORT}
        - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
        - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
        - SERVER_VIRTUAL_HOST=${SERVER_VIRTUAL_HOST}
        - SERVER_VIRTUAL_PORT=${SERVER_VIRTUAL_PORT}
        - SERVER_LETSENCRYPT_HOST=${SERVER_LETSENCRYPT_HOST}
        - SERVER_LETSENCRYPT_EMAIL=${SERVER_LETSENCRYPT_EMAIL}
        - AUTH_JWT_SECRET_KEY=${AUTH_JWT_SECRET_KEY}
        - AUTH_EMAIL_VERIFICATION_SECRET_KEY=${AUTH_EMAIL_VERIFICATION_SECRET_KEY}
        - RESET_PASSWORD_JWT_SECRET_KEY=${RESET_PASSWORD_JWT_SECRET_KEY}
        - RESET_PASSWORD_EXPIRATION_DELAY=${RESET_PASSWORD_EXPIRATION_DELAY}
        - MAIL_SENDER=${MAIL_SENDER}
        - MAIL_FROM=${MAIL_FROM}
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_USER=${MAIL_USER}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      VIRTUAL_HOST: ${SERVER_VIRTUAL_HOST}
      VIRTUAL_PORT: ${SERVER_VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${SERVER_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${SERVER_LETSENCRYPT_EMAIL}
    networks:
      - webappnetwork
      - default

networks:
  default:
    external:
      name: nginx-proxy
  webappnetwork:
    driver: bridge
