version: "3"
services:
  media:
    ports:
      - 3001:3001
    build:
      context: ../mbi
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: ${MEDIA_PORT}
      VIRTUAL_HOST: ${NEXT_PUBLIC_UPLOAD_URL}
      VIRTUAL_PORT: ${CLIENT_VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${NEXT_PUBLIC_UPLOAD_URL}
      LETSENCRYPT_EMAIL: ${CLIENT_LETSENCRYPT_EMAIL}
    volumes:
      - "./public:/usr/src/app/public"
    networks:
      - default
  app:
    ports:
      - 3000:3000
    build:
      context: ../app
    restart: always
    env_file:
      - ./.env
    environment:
      NEXT_PUBLIC_UPLOAD_URL: ${NEXT_PUBLIC_UPLOAD_URL}
      VIRTUAL_HOST: ${CLIENT_VIRTUAL_HOST}
      VIRTUAL_PORT: ${CLIENT_VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${CLIENT_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${CLIENT_LETSENCRYPT_EMAIL}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - media
    networks:
      - default

networks:
  default:
    external:
      name: nginx-proxy
  webappnetwork:
    driver: bridge
